### PR TITLE
fix syntax error in Turkish Translation.

### PR DESCRIPTION
**Pull request by CakirEfekan**
fix syntax error in Turkish translation due to "GitHub'da"

### CODE REVIEW

**Comment by yrccondor** [comment]
Hi,
Thanks for the contribution and sorry for the delay, but I didn't know what is broken and why this change can fix the translation. Could you please provide more information?

**Comment by CakirEfekan** [comment]
Hi,

Single quote is being used to seperate proper noun and its suffix in Turkish. Also in Turkish translation there is a sentence like that: https://github.com/yrccondor/mdx/blob/81ed531238827a1b4abe19df0011b4bd7d86b70c/languages/tr_TR.po#L1654-L1656

The sentence breaks the footer, I fixed when I replaced the quotation marks in footer.  If there is a better solution, I do not know that.

Actually, thanks for the perfect theme! 👍

**Comment by yechs** [comment]
Alternatively, you can use `&#39;` or `&apos;` to escape the single quotes inside translated text

**Comment by yrccondor** [comment]
Thank you for clarifying. A better solution is to use `htmlspecialchars` function to aviod breaking the string. I'll close this pr and update `footer.php` soon.

**Comment by yrccondor** [comment]
fixed in 6d5bbff

**Pull request closed without merging**
